<?php

//create sale
//id, invoice_number, summation, tax, currency, paid(bool)
class Sale
{
    public function createSale()
    {
        //logic for create sale
    }
}

class RentalSale extends Sale
{
    public function createSale()
    {
        parent::createSale(); // TODO: Change the autogenerated stub

        //logic for rental sale
    }
}

//new requirement
//rental sale
//create sale
//save rental schema 12 month, 24 months, $monthly payment