<?php

class Calculation
{
    final public function sum(int $i, int $y): int
    {
        return $i + $y;
    }
}

class MyCalculation extends Calculation
{
    public function sum(int $i, int $y): int
    {
        $i = $i * 10;

        return parent::sum($i, $y); // TODO: Change the autogenerated stub
    }
}

$calculationObj = new Calculation();
var_dump($calculationObj->sum(5, 10));
$calculationObj2 = new MyCalculation();
var_dump($calculationObj2->sum(5, 10));

