<?php
class User
{
    public function __construct(
        private string $country,
        private string $name = ''
    )
    {
    }

    //php7.4 and before
//    private string $country;
//    private string $name;
//
//    public function __construct(string $country, string $name = '')
//    {
//        $this->country = $country;
//        $this->name = $name;
//    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function printUserName(): string
    {
        return $this->name;
    }

    public function printCountryName(): string
    {
        return $this->country;
    }

    final public function changeCountry(string $country): void
    {
        $this->country = $country;
    }

    public function __destruct()
    {
        //any operation
        //garpage collection
        //unset($this->country)
    }
}
//
//class UserProfile extends User
//{
//    public function changeCountry(string $country): void
//    {
//        parent::changeCountry($country); // TODO: Change the autogenerated stub
//    }
//}

//instantiating objects
//$userObj = new User('Palestine', 'Mohammed');
////var_dump($userObj->printUserName());
//
//$newObject = clone $userObj;
//
//$newObject->setName('Jameel');
//var_dump($newObject);
//var_dump($userObj);
//var_dump($newObject->printUserName());
//var_dump($userObj->printUserName());
//var_dump($userObj->printCountryName());
//$userObj->changeCountry('Malaysia');
//var_dump($userObj->printCountryName());


//function sum(&$num)
//{
//    $num += 20;
//
//    echo $num . "\n";
//}
//$number = 10;
//sum($number);
//
////case one - call by value
////$number = 10
////$num = 30
//
////case one - call by reference
////$number = 30
//
//echo $number . "\n";

//------------------------
class Address
{
    protected string $city;
    protected string $country;

    public function setCity($city): string
    {
        return $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCity(): string
    {
        return $this->city;
    }

    public function setCountry($country): string
    {
        return $this->country = $country;
    }

    /**
     * @return string
     */
    public function getCountry(): string
    {
        return $this->country;
    }
}

class Person
{
    protected string $name;
    protected Address $address;

    public function __construct()
    {
        $this->address = new Address();
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    public function __call(string $name, array $arguments)
    {
        if (method_exists($this->address, $name)) {
            return call_user_func_array(array($this->address, $name), $arguments);
        }
    }

    public function __clone(): void
    {
        $this->address = clone  $this->address;
    }
}


$jameel = new Person();
$jameel->setName('Jameel S');
$jameel->setCity('Gaza');

$mohammed = clone $jameel;
$mohammed->setName('Mohammed J');
$mohammed->setCity('Malaysia');

print $jameel->getName() . ' lives in ' . $jameel->getCity() . "\n";
print $mohammed->getName() . ' lives in ' . $mohammed->getCity() . "\n";



